GamePlayManager={
  init:function(){
    console.log("Init");
    game.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;
    game.scale.pageAlignHorizontally=true;
    game.scale.pageAlignVertically=true;
  },
  preload:function(){
    console.log("Preaload");
    game.load.image('background','assets/images/background.png');
    game.load.spritesheet('horse','assets/images/horse.png',84,156,2);
  },
  create:function(){
    console.log("create");
    game.add.sprite(0,0,'background');
    this.horse=game.add.sprite(0,0,'horse');
    this.horse.frame=1;
    this.horse.x=game.width/2;
    this.horse.y=game.height/2;
  },
  update:function(){
    console.log("update");
  }
}
var game=new Phaser.Game(1136,640,Phaser.AUTO);
game.state.add('gameplay',GamePlayManager);
game.state.start("gameplay");
